export const BASE_URL = "https://www.canevimsile.com";

export const menuLandings = [
  { slug: "sile-serpme-kahvalti", name: "Şile Serpme Kahvaltı", menuName: "Serpme Kahvaltı", anchor: "kahvalti", image: "/images/serpme.jpeg", description: "Şile Üvezli'de doğayla iç içe, pişi, menemen, yumurta, peynir çeşitleri ve sınırsız çayla sunulan serpme kahvaltı deneyimi.", intro: "Can Evim'in serpme kahvaltısı; sıcakları, yöresel eşlikçileri ve uzun sofralara yakışan sınırsız çayı aynı masada buluşturur.", highlights: ["Doğayla iç içe bahçe", "Geleneksel kahvaltı sıcakları", "Her gün 08:00–23:00"] },
  { slug: "sile-koy-kahvaltisi", name: "Şile Köy Kahvaltısı", menuName: "Kahvaltı", anchor: "kahvalti", image: "/assets/images/serpme_kahvalti.jpg", description: "Şile'de köy kahvaltısı arayanlar için Üvezli'de taze, yöresel ve sıcak ürünlerle hazırlanan Can Evim kahvaltı menüsü.", intro: "Şile'nin sakinliğinde kurulan köy kahvaltısı soframız, yerel tatları ve sıcak ürünleri özenli bir sunumla bir araya getirir.", highlights: ["Üvezli'de sakin konum", "Taze ve yöresel seçkiler", "Aile ve arkadaş sofraları"] },
  { slug: "sile-gozleme", name: "Şile Gözleme", menuName: "Gözleme Çeşitleri", anchor: "ana-yemekler", image: "/assets/images/gozleme.jpg", description: "Şile'de patatesli, kaşarlı, beyaz peynirli, pazılı, kıymalı ve sucuklu gözleme çeşitlerini Can Evim menüsünde keşfedin.", intro: "İnce açılmış hamur ve sevilen iç harçlarla hazırlanan gözlemelerimiz kahvaltıya ya da gün içindeki molanıza eşlik eder.", highlights: ["Altı farklı iç seçenek", "Sipariş üzerine sıcak servis", "Kahvaltı ve ana yemek menüsüyle uyumlu"] },
  { slug: "sile-ev-yapimi-manti", name: "Şile Ev Yapımı Mantı", menuName: "Ev Yapımı Mantı", anchor: "ana-yemekler", image: "/images/manti.jpg", description: "Şile'de ev yapımı mantı ve çıtır mantı için Can Evim Üvezli menüsünü inceleyin; yol tarifi ve rezervasyon bilgilerine ulaşın.", intro: "Geleneksel mutfağın sevilen lezzeti ev yapımı mantıyı, Can Evim'in sakin bahçe atmosferinde sofranıza getiriyoruz.", highlights: ["Geleneksel reçete", "Ev yapımı lezzet", "Üvezli Şile'de kolay ulaşım"] },
  { slug: "sile-izgara-sac-kavurma", name: "Şile Izgara ve Sac Kavurma", menuName: "Izgara Etler ve Sac Kavurma", anchor: "izgara", image: "/assets/images/sac_kavurma.jpg", description: "Şile Üvezli'de ızgara köfte, ızgara sucuk, piliç ızgara ve sac kavurma seçenekleri için Can Evim ana yemek menüsünü inceleyin.", intro: "Izgara köfte, ızgara sucuk, piliç ızgara ve sac kavurmayı bir araya getiren ana yemek seçkimiz, gün boyu doyurucu bir sofra alternatifi sunar.", highlights: ["Menüdeki gerçek ızgara seçenekleri", "Doğa içindeki aile sofraları", "Her gün 08:00–23:00"] },
  { slug: "sile-aile-restorani", name: "Şile Aile Restoranı", menuName: "Kahvaltı ve Ana Yemekler", anchor: "kahvalti", image: "/images/kesinkullan3.jpeg", description: "Şile'de ailece kahvaltı ve yemek için Üvezli'deki Can Evim'in doğa içindeki ortamını ve güncel menüsünü keşfedin.", intro: "Farklı damak zevklerini buluşturan kahvaltı, gözleme, mantı ve ızgara seçeneklerimizle aile sofralarına doğa içinde sakin bir alan sunuyoruz.", highlights: ["Kahvaltı ve ana yemek çeşitliliği", "Doğa içinde açık alan", "Rezervasyon ve yol tarifi"] },
  { slug: "sile-yolu-kahvalti-restoran", name: "Şile Yolu Kahvaltı ve Restoran", menuName: "Can Evim Menüsü", anchor: "kahvalti", image: "/images/kesinkullan.jpeg", description: "Şile Yolu üzerinde Üvezli'de kahvaltı ve restoran molası: Can Evim menüsü, adresi, çalışma saatleri ve yol tarifi.", intro: "Şile Yolu üzerindeki Üvezli konumumuzda kahvaltıdan ana yemeğe uzanan menümüzle doğa içinde sakin bir mola sunuyoruz.", highlights: ["Şile Yolu üzerindeki Üvezli konumu", "Her gün 08:00–23:00", "Kahvaltı ve ana yemek"] },
];

export const blogPosts = [
  { slug: "silede-kahvalti-rehberi", title: "Şile'de Kahvaltı Rehberi: Doğada Uzun Bir Sofra", excerpt: "Şile'de kahvaltı planlarken konum, menü ve rezervasyon açısından nelere dikkat edilmeli?", image: "/images/serpme.jpeg", date: "2026-08-08", sections: [["Şile'de kahvaltı neden farklı?", "Şile, şehirden uzaklaşmadan doğayla buluşmak isteyenler için güçlü bir hafta sonu rotasıdır. Üvezli gibi sakin bölgelerde kahvaltı, yalnızca yemek değil uzun ve huzurlu bir sofra deneyimine dönüşür."], ["Sofrada neler aranmalı?", "Peynir, zeytin ve reçellerin yanında pişi, yumurta, menemen ve sıcak ürünlerin dengeli sunulması önemlidir. Can Evim'in güncel seçeneklerini Şile serpme kahvaltı sayfamızdan inceleyebilirsiniz."]], links: ["sile-serpme-kahvalti", "sile-koy-kahvaltisi"] },
  { slug: "serpme-kahvaltida-neler-var", title: "Serpme Kahvaltıda Neler Var?", excerpt: "İyi bir serpme kahvaltının temel ürünleri, sıcakları ve sunum dengesi.", image: "/assets/images/serpme_kahvalti.jpg", date: "2026-08-08", sections: [["Temel kahvaltılıklar", "Peynirler, zeytinler, domates, salatalık, tereyağı, bal-kaymak ve reçeller sofranın temelini kurar."], ["Sıcakların rolü", "Pişi, muska börek, sahanda yumurta ve menemen sofrayı tamamlar. Sınırsız çay ise uzun kahvaltı sohbetlerine eşlik eder."]], links: ["sile-serpme-kahvalti", "sile-koy-kahvaltisi"] },
  { slug: "uvezlide-hafta-sonu-kahvaltisi", title: "Üvezli'de Hafta Sonu Kahvaltısı Planı", excerpt: "Üvezli'ye ulaşım, doğru saat seçimi ve doğada kahvaltı için kısa plan.", image: "/images/kesinkullan.jpeg", date: "2026-08-08", sections: [["Doğru saat", "Hafta sonu kahvaltısında daha sakin bir deneyim için erken saatleri tercih etmek ve kalabalık gruplarda rezervasyon yapmak faydalıdır."], ["Konum avantajı", "Can Evim, Üvezli Mahallesi Şile Yolu Caddesi üzerinde doğa içinde bir mola sunar ve her gün 08:00'de açılır."]], links: ["sile-koy-kahvaltisi", "sile-serpme-kahvalti"] },
  { slug: "mihlama-kuymak-farki", title: "Mıhlama ile Kuymak Arasındaki Fark Nedir?", excerpt: "İki sevilen Karadeniz lezzetinin isim, yöre ve hazırlanış yaklaşımına kısa bakış.", image: "/assets/images/menemen_mihlama.jpg", date: "2026-08-08", sections: [["İsim ve yöre", "Mıhlama ve kuymak adları bölgeden bölgeye farklı kullanılır. Her iki tarifte de peynir, yağ ve mısır unu dengesi belirleyicidir."], ["Kahvaltıdaki yeri", "Sıcak ve paylaşmaya uygun yapısıyla mıhlama, serpme kahvaltının en sevilen ek seçeneklerinden biridir."]], links: ["sile-serpme-kahvalti", "sile-koy-kahvaltisi"] },
  { slug: "silede-aile-restorani-secimi", title: "Şile'de Aile Restoranı Seçerken Nelere Bakılmalı?", excerpt: "Menü çeşitliliği, açık alan, ulaşım ve çalışma saatleriyle ailece doğru mekân seçimi.", image: "/images/kesinkullan3.jpeg", date: "2026-08-08", sections: [["Farklı tercihlere uygun menü", "Aile sofralarında kahvaltının yanında gözleme, mantı ve ızgara gibi seçeneklerin bulunması farklı damak zevklerini karşılar."], ["Mekân ve zaman", "Doğayla iç içe açık alan, net çalışma saatleri ve kolay yol tarifi planlamayı kolaylaştırır."]], links: ["sile-aile-restorani", "sile-gozleme", "sile-izgara-sac-kavurma"] },
  { slug: "sile-gozleme-cesitleri", title: "Şile'de Gözleme Çeşitleri: Hangi İç Harcı Seçmeli?", excerpt: "Patatesli, peynirli, pazılı, kıymalı ve sucuklu gözleme seçenekleri.", image: "/assets/images/gozleme.jpg", date: "2026-08-08", sections: [["Klasik seçenekler", "Patatesli ve peynirli gözleme sade ve dengeli seçeneklerdir; pazılı gözleme yeşillik sevenlere hitap eder."], ["Daha doyurucu tercihler", "Kıymalı ve sucuklu seçenekler daha güçlü bir ana öğün isteyenler için öne çıkar."]], links: ["sile-gozleme", "sile-koy-kahvaltisi"] },
];

export function getMenuLanding(slug) { return menuLandings.find((item) => item.slug === slug); }
export function getBlogPost(slug) { return blogPosts.find((post) => post.slug === slug); }
