import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { BASE_URL, blogPosts, getBlogPost, getMenuLanding } from "../../seo-data";

export const dynamicParams = false;
export function generateStaticParams() { return blogPosts.map(({ slug }) => ({ slug })); }
export async function generateMetadata({ params }) { const { slug } = await params; const post = getBlogPost(slug); if (!post) return {}; const path = `/blog/${post.slug}`; return { title: `${post.title} | Can Evim Şile`, description: post.excerpt, alternates: { canonical: path }, openGraph: { title: post.title, description: post.excerpt, url: path, type: "article", images: [{ url: post.image, alt: post.title }] } }; }

export default async function BlogPost({ params }) {
  const { slug } = await params; const post = getBlogPost(slug); if (!post) notFound(); const url = `${BASE_URL}/blog/${post.slug}`;
  const schema = [{ "@context": "https://schema.org", "@type": "BlogPosting", headline: post.title, description: post.excerpt, image: `${BASE_URL}${post.image}`, datePublished: post.date, dateModified: post.date, mainEntityOfPage: url, author: { "@type": "Organization", name: "Can Evim Şile" }, publisher: { "@id": `${BASE_URL}/#restaurant` } }, { "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Can Evim Şile", item: `${BASE_URL}/` }, { "@type": "ListItem", position: 2, name: "Blog", item: `${BASE_URL}/blog` }, { "@type": "ListItem", position: 3, name: post.title, item: url }] }];
  return <main className="min-h-screen bg-[#fcfaf7] text-[#222]"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema).replace(/</g, "\\u003c") }} /><div className="relative h-[58vh] min-h-[450px]"><Image src={post.image} alt={post.title} fill priority className="object-cover" /><div className="absolute inset-0 bg-black/45" /><div className="absolute inset-0 flex items-end"><header className="w-full max-w-[1000px] mx-auto px-6 md:px-12 pb-14 text-white"><nav className="font-sans text-xs tracking-widest uppercase mb-6"><Link href="/">Ana Sayfa</Link> / <Link href="/blog">Rehber</Link></nav><h1 className="font-serif text-4xl md:text-7xl leading-tight">{post.title}</h1></header></div></div><article className="max-w-[800px] mx-auto px-6 py-16 md:py-24">{post.sections.map(([heading, body]) => <section key={heading} className="mb-12"><h2 className="font-serif text-3xl md:text-4xl mb-5">{heading}</h2><p className="font-serif text-lg leading-[1.9] text-[#4b4b48]">{body}</p></section>)}<aside className="mt-16 border-t border-[#d8d2c8] pt-9"><p className="font-sans text-xs tracking-[0.25em] uppercase text-[#9a793d] mb-6">İlgili menü seçenekleri</p><div className="flex flex-wrap gap-3">{post.links.map((linkedSlug) => { const item = getMenuLanding(linkedSlug); return <Link key={linkedSlug} href={`/lezzetler/${linkedSlug}`} className="border border-[#c9c1b4] px-5 py-3 font-serif">{item.name}</Link>; })}</div><div className="flex flex-wrap gap-3 mt-5"><Link href="/menu#kahvalti" className="border border-[#222] bg-[#222] text-white px-5 py-3 font-serif">Güncel menüyü incele</Link><a href="https://www.google.com/maps/search/?api=1&query=Can+Evim+Şile" target="_blank" rel="noreferrer" className="border border-[#c9c1b4] px-5 py-3 font-serif">Yol tarifi al</a></div></aside></article></main>;
}
